<a href="https://colab.research.google.com/github/auchisam889-afk/AuChiSam_2305CT2055/blob/main/Tuan_1_2305CT2055_AuChiSam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
import sys

print("Python version :", sys.version.split()[0])
print("Interpreter    :", sys.executable)

major = sys.version_info.major
minor = sys.version_info.minor
print(f"Python major/minor: {major}.{minor}")
print(f"Python >= 3.11 : {(major, minor) >= (3, 11)}")

Python version : 3.13.15
Interpreter    : /usr/bin/python3
Python major/minor: 3.13
Python >= 3.11 : True


In [62]:
LIBS = {
    "numpy":        "numpy",
    "pandas":       "pandas",
    "matplotlib":   "matplotlib",
    "seaborn":      "seaborn",
    "scikit-learn": "sklearn",
}

import numpy as np
import pandas as pd
import matplotlib
import seaborn
import sklearn

print("numpy      :", np.__version__)
print("pandas     :", pd.__version__)

print("matplotlib  :", matplotlib.__version__)
print("seaborn     :", seaborn.__version__)
print("scikit-learn:", sklearn.__version__)

numpy      : 2.1.3
pandas     : 2.2.3
matplotlib  : 3.10.0
seaborn     : 0.13.2
scikit-learn: 1.6.1


In [63]:
import importlib

versions = {}
for pip_name, import_name in LIBS.items():
  try:
        mod = importlib.import_module(import_name)
        versions[pip_name] = getattr(mod, "__version__", "?")
        print(f"PASS  {pip_name:<14} {versions[pip_name]}")
  except ImportError:
        versions[pip_name] = None
        print(f"FAIL  {pip_name:<14} chưa cài  ->  pip install {pip_name}")
  pass

print()
print("Số thư viện PASS:", sum(v is not None for v in versions.values()), "/", len(LIBS))

PASS  numpy          2.1.3
PASS  pandas         2.2.3
PASS  matplotlib     3.10.0
PASS  seaborn        0.13.2
PASS  scikit-learn   1.6.1

Số thư viện PASS: 5 / 5


In [64]:
thieu = [name for name, v in versions.items() if v is None]
assert not thieu, "Thiếu thư viện: " + ", ".join(thieu) + " -> pip install " + " ".join(thieu)
assert sys.version_info >= (3, 11), "Cần Python >= 3.11, đang chạy " + sys.version.split()[0]

print("Bài 1 OK - môi trường đã sẵn sàng.")

Bài 1 OK - môi trường đã sẵn sàng.


In [65]:
import numpy as np

rng = np.random.default_rng(42)

X = rng.standard_normal((1000, 5))

print("shape :", X.shape)
print("ndim  :", X.ndim)
print("dtype :", X.dtype)
print("nbytes:", X.nbytes, "byte =", X.nbytes / 1024, "KB")
print("Một phần tử chiếm:", X.itemsize, "byte")

shape : (1000, 5)
ndim  : 2
dtype : float64
nbytes: 40000 byte = 39.0625 KB
Một phần tử chiếm: 8 byte


In [66]:
assert X.shape == (1000, 5), f"shape sai: {X.shape}"
assert X.ndim == 2, "Phải là mảng 2 chiều"
assert X.dtype == np.float64, f"dtype sai: {X.dtype}"
assert X.nbytes == 1000 * 5 * 8, "nbytes = số phần tử x 8 byte (float64)"

print("2.1 OK - 1000 x 5 x 8 byte =", X.nbytes, "byte")

2.1 OK - 1000 x 5 x 8 byte = 40000 byte


In [67]:
S = np.arange(12).reshape(3, 4)
print(S)
print()

print("S.sum(axis=0) =", S.sum(axis=0), "| shape", S.sum(axis=0).shape,
      "<- gộp CÁC DÒNG lại, còn một số cho mỗi CỘT")
print("S.sum(axis=1) =", S.sum(axis=1), "| shape", S.sum(axis=1).shape,
      "<- gộp CÁC CỘT lại, còn một số cho mỗi DÒNG")

print("S.mean(axis=0) =", S.mean(axis=0), "| shape", S.mean(axis=0).shape)
print("S.max(axis=1)  =", S.max(axis=1), "| shape", S.max(axis=1).shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

S.sum(axis=0) = [12 15 18 21] | shape (4,) <- gộp CÁC DÒNG lại, còn một số cho mỗi CỘT
S.sum(axis=1) = [ 6 22 38] | shape (3,) <- gộp CÁC CỘT lại, còn một số cho mỗi DÒNG
S.mean(axis=0) = [4. 5. 6. 7.] | shape (4,)
S.max(axis=1)  = [ 3  7 11] | shape (3,)


In [68]:
print("Trung bình từng cột (axis=0):", X.mean(axis=0).round(4))
print("Độ lệch chuẩn từng cột      :", X.std(axis=0).round(4))
print("shape của kết quả           :", X.mean(axis=0).shape, "<- 5 số, một số / cột")

print("Min toàn mảng               :", X.min().round(4))
print("Max toàn mảng               :", X.max().round(4))

Trung bình từng cột (axis=0): [-0.0457  0.0092  0.0031 -0.0244 -0.0416]
Độ lệch chuẩn từng cột      : [1.     1.0354 0.9669 1.0183 0.9732]
shape của kết quả           : (5,) <- 5 số, một số / cột
Min toàn mảng               : -3.6484
Max toàn mảng               : 3.454


In [69]:
Xs = (X - X.mean(axis=0)) / X.std(axis=0)

print("Trung bình sau chuẩn hóa  :", Xs.mean(axis=0).round(12))
print("Độ lệch chuẩn sau chuẩn hóa:", Xs.std(axis=0).round(12))
print("shape giữ nguyên          :", Xs.shape)

Trung bình sau chuẩn hóa  : [ 0.  0. -0. -0. -0.]
Độ lệch chuẩn sau chuẩn hóa: [1. 1. 1. 1. 1.]
shape giữ nguyên          : (1000, 5)


In [70]:
assert Xs.shape == X.shape, "Chuẩn hóa không được đổi shape"
assert np.abs(Xs.mean(axis=0)).max() < 1e-9, "Trung bình từng cột phải xấp xỉ 0"
assert np.abs(Xs.std(axis=0) - 1).max() < 1e-9, "Độ lệch chuẩn từng cột phải xấp xỉ 1"

print(f"2.5 OK - sai số trung bình lớn nhất: {np.abs(Xs.mean(axis=0)).max():.2e}")
print(f"         sai số độ lệch chuẩn lớn nhất: {np.abs(Xs.std(axis=0) - 1).max():.2e}")
print("Hai con số trên KHÁC 0 - số dấu phẩy động là thế, nên mới so với 1e-9 chứ không so == 0.")

2.5 OK - sai số trung bình lớn nhất: 2.88e-17
         sai số độ lệch chuẩn lớn nhất: 6.66e-16
Hai con số trên KHÁC 0 - số dấu phẩy động là thế, nên mới so với 1e-9 chứ không so == 0.


In [71]:
import time

def chuan_hoa_vong_lap(A):
    '''Chuẩn hóa từng cột bằng vòng lặp Python thuần — cách CHẬM.'''
    n_dong, n_cot = A.shape
    out = np.empty_like(A)
    for j in range(n_cot):
        cot = [A[i, j] for i in range(n_dong)]
        tb = sum(cot) / n_dong
        do_lech = (sum((v - tb) ** 2 for v in cot) / n_dong) ** 0.5
        for i in range(n_dong):
            out[i, j] = (A[i, j] - tb) / do_lech
    return out

def chuan_hoa_vector(A):
    return (A - A.mean(axis=0)) / A.std(axis=0)

# 2.7 — hai cách làm cùng một việc
import time

def chuan_hoa_vong_lap(A):
    '''Chuẩn hóa từng cột bằng vòng lặp Python thuần — cách CHẬM.'''
    n_dong, n_cot = A.shape
    out = np.empty_like(A)
    for j in range(n_cot):
        cot = [A[i, j] for i in range(n_dong)]
        tb = sum(cot) / n_dong
        do_lech = (sum((v - tb) ** 2 for v in cot) / n_dong) ** 0.5
        for i in range(n_dong):
            out[i, j] = (A[i, j] - tb) / do_lech
    return out

print("Đã định nghĩa 2 hàm.")


Đã định nghĩa 2 hàm.


In [72]:
t0 = time.perf_counter()
X_loop = chuan_hoa_vong_lap(X)
t_loop = time.perf_counter() - t0

N_LAP = 100
t0 = time.perf_counter()
for _ in range(N_LAP):
    X_vec = chuan_hoa_vector(X)
t_vec = (time.perf_counter() - t0) / N_LAP

print(f"Vòng lặp Python  : {t_loop * 1000:9.3f} ms")
print(f"Vector hóa NumPy : {t_vec  * 1000:9.4f} ms  (trung bình {N_LAP} lần chạy)")
print(f"Nhanh hơn        : {t_loop / t_vec:9.1f} lần")


Vòng lặp Python  :     8.142 ms
Vector hóa NumPy :    0.1782 ms  (trung bình 100 lần chạy)
Nhanh hơn        :      45.7 lần


In [73]:
assert np.allclose(X_loop, X_vec), "Hai cách phải cho cùng một kết quả"
assert np.allclose(X_vec, Xs), "...và phải khớp với Xs tính ở ô 2.5"

speedup = t_loop / t_vec
assert speedup > 5, f"Chỉ nhanh hơn {speedup:.1f} lần — kiểm tra lại chuan_hoa_vector"

print(f"2.7 OK — hai cách cho cùng kết quả, vector hóa nhanh hơn {speedup:.0f} lần.")
print("Nhanh mà sai thì vô dụng: luôn kiểm tra kết quả trước, đo tốc độ sau.")


2.7 OK — hai cách cho cùng kết quả, vector hóa nhanh hơn 46 lần.
Nhanh mà sai thì vô dụng: luôn kiểm tra kết quả trước, đo tốc độ sau.


In [74]:
from pathlib import Path
import pandas as pd

UNG_VIEN = [
    Path("C:\User\PM401\Desktop\lab_exercises\lab_data\sinhvien.csv"),
    Path("lab_data\sinhvien.csv"),
    Path("sinhvien.csv"),
]
CSV_PATH = next((p for p in UNG_VIEN if p.exists()), None)

if CSV_PATH is None:
    raise FileNotFoundError(
        "Không tìm thấy sinhvien.csv.\n"
        "Notebook phải nằm trong thư mục lab_exercises/, CẠNH thư mục lab_data/.\n"
        "Thư mục hiện tại : " + str(Path.cwd()) + "\n"
        "Đã thử các đường dẫn: " + ", ".join(str(p) for p in UNG_VIEN)
    )

df = pd.read_csv(CSV_PATH)
print("Đã nạp:", CSV_PATH.resolve())
df.head()


SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (2561905616.py, line 5)

In [75]:
print("Số dòng:", df.shape[0])
print("Số cột :", df.shape[1])
print("Tên cột:", list(df.columns))

print("\n--- Kiểu dữ liệu từng cột ---")
print(df.dtypes)

print("\n--- Số giá trị thiếu của từng cột ---")
print(df.isna().sum())

print("\n--- Tỉ lệ thiếu của từng cột (%) ---")
print((df.isna().mean() * 100).round(2))

NameError: name 'df' is not defined

In [76]:
print("dtype của mssv khi read_csv đọc mặc định:", df["mssv"].dtype)
print("Một giá trị     :", df["mssv"].iloc[0], "->", type(df["mssv"].iloc[0]).__name__)
print()
print("Trung bình cộng MSSV:", df["mssv"].mean())
print("MSSV lớn nhất       :", df["mssv"].max())
print()
print("Hai con số trên tính được, nhưng KHÔNG CÓ NGHĨA GÌ.")
print("MSSV là ĐỊNH DANH: không cộng, không trừ, không lấy trung bình.")


NameError: name 'df' is not defined

In [77]:
df = pd.read_csv(CSV_PATH, dtype={"mssv": str})

print("dtype sau khi sửa:", df["mssv"].dtype)
print("Một giá trị       :", repr(df["mssv"].iloc[0]))
print("shape             :", df.shape)

ValueError: Invalid file path or buffer object type: <class 'NoneType'>

In [78]:
assert isinstance(df["mssv"].iloc[0], str), "mssv phải là chuỗi, không phải số"
assert df["mssv"].iloc[0] == "2200001", "Giá trị đầu tiên phải là chuỗi '2200001'"
assert df.shape == (1200, 9), f"Dữ liệu phải có 1200 dòng x 9 cột, đang là {df.shape}"
assert df["mssv"].duplicated().sum() == 0, "MSSV phải là duy nhất"
assert df["gpa"].isna().sum() == 55, "Phải có đúng 55 sinh viên thiếu GPA"

print("3.3 OK — mssv giờ là định danh dạng chuỗi; 1200 mã, không trùng.")


NameError: name 'df' is not defined

In [79]:
mask_1 = (df["khoa"] == "Kỹ thuật Công nghệ") & (df["gpa"] >= 3.2)
cau_1 = df.loc[mask_1, ["mssv", "ho_ten", "nam_hoc", "gpa"]]

print("Số sinh viên:", len(cau_1))
print("GPA trung bình của nhóm này:", round(cau_1["gpa"].mean(), 3))
cau_1.sort_values("gpa", ascending=False).head(5)

NameError: name 'df' is not defined

In [80]:
cau_2 = df.groupby("khoa")["gio_tu_hoc"].mean().sort_values(ascending=False)

print(cau_2.round(2))
print()
print("Cao nhất :", cau_2.idxmax(), "-", round(cau_2.max(), 2), "giờ/tuần")
print("Thấp nhất:", cau_2.idxmin(), "-", round(cau_2.min(), 2), "giờ/tuần")
print("Chênh lệch:", round(cau_2.max() - cau_2.min(), 2), "giờ/tuần")

NameError: name 'df' is not defined

In [81]:
mask_3 = (df["nam_hoc"] == 3) & (df["tinh_tp"] == "TP. Hồ Chí Minh")

so_luong_3 = int(mask_3.sum())
tong_nam_3 = int((df["nam_hoc"] == 3).sum())

print("Sinh viên năm 3 quê TP. Hồ Chí Minh:", so_luong_3)
print("Tổng sinh viên năm 3               :", tong_nam_3)
print("Chiếm:", round(100 * so_luong_3 / tong_nam_3, 1), "%")

NameError: name 'df' is not defined

In [82]:
cau_4 = df.nlargest(10, "gpa")[["mssv", "ho_ten", "khoa", "nam_hoc", "gpa"]]

print("Số dòng:", len(cau_4))
print("GPA cao nhất:", cau_4["gpa"].max(), "| GPA thấp nhất trong top 10:", cau_4["gpa"].min())
cau_4

NameError: name 'df' is not defined

In [83]:
cau_5 = df.loc[df["gpa"].isna()]

print("Số sinh viên thiếu GPA:", len(cau_5))
print("Tỉ lệ:", round(100 * len(cau_5) / len(df), 2), "%")
print()
print("Các em này vẫn có đủ thông tin khác:")
cau_5[["mssv", "ho_ten", "khoa", "nam_hoc", "so_tin_chi", "gpa"]].head(8)

NameError: name 'df' is not defined

In [84]:
# 3.10 — tự kiểm tra cả 5 câu. Chạy im lặng = cả 5 đều đúng.
assert len(cau_1) == 35, f"Câu 1 phải ra 35 sinh viên, bạn ra {len(cau_1)}"
assert cau_2.idxmax() == "Luật", "Câu 2: khoa tự học nhiều nhất phải là Luật"
assert cau_2.idxmin() == "Kỹ thuật Công nghệ", "Câu 2: thấp nhất phải là Kỹ thuật Công nghệ"
assert abs(cau_2.max() - 8.98) < 0.01, "Câu 2: giá trị cao nhất phải xấp xỉ 8.98"
assert so_luong_3 == 120, f"Câu 3 phải ra 120, bạn ra {so_luong_3}"
assert len(cau_4) == 10, "Câu 4 phải trả về đúng 10 dòng"
assert cau_4["gpa"].max() == 4.0, "Câu 4: GPA cao nhất phải là 4.0"
assert round(float(cau_4["gpa"].min()), 2) == 3.78, "Câu 4: GPA thứ 10 phải là 3.78"
assert len(cau_5) == 55, f"Câu 5 phải ra 55 sinh viên, bạn ra {len(cau_5)}"

print("Bài 3 OK — cả 5 câu đều khớp với dữ liệu.")


NameError: name 'cau_1' is not defined

In [85]:
import shutil
import subprocess


def chay(*lenh):
    r = subprocess.run(lenh, capture_output=True, text=True)
    return r.returncode, (r.stdout + r.stderr).strip()


if shutil.which("git") is None:
    print("FAIL  git chưa được cài. Tải tại https://git-scm.com/downloads")
else:
    print("PASS  ", chay("git", "--version")[1])

    ma, ket_qua = chay("git", "rev-parse", "--is-inside-work-tree")
    if ma == 0 and ket_qua == "true":
        print("PASS   Thư mục này đã là một Git repository.")

        log = chay("git", "log", "--oneline", "-n", "3")[1]
        print("PASS   Commit gần nhất:" if log else "CHƯA   Chưa có commit nào — chạy git commit")
        print(log or "       (trống)")

        remote = chay("git", "remote", "-v")[1]
        print("\nRemote:")
        print(remote or "       (chưa có remote — chạy git remote add origin <url>)")
    else:
        print("CHƯA   Chưa phải Git repository.")
        print("       Mở Terminal tại thư mục lab_exercises/ rồi chạy: git init")


PASS   git version 2.43.0
CHƯA   Chưa phải Git repository.
       Mở Terminal tại thư mục lab_exercises/ rồi chạy: git init
